### PR TITLE
fix: add style prop to AvatarText

### LINKED ISSUE #1136: textStyle prop for Avatar.Text
## Describe the feature
a textStyle prop for Avatar.Text so you can style the text inside the avatar.

## Motivation
Need to Italicize / Bolden the Avatar text.

### PR DESCRIPTION
**Pull request by wojteg1337**
### Motivation

This pr fixes #1136 

Added prop for avatar text to add custom text style.

### CODE REVIEW

File: src/components/Avatar/AvatarText.tsx [hunk 1]
```diff
@@ -55,7 +68,7 @@ class AvatarText extends React.Component<Props> {
   };
 
   render() {
-    const { label, size = defaultSize, style, theme } = this.props;
+    const { label, size = defaultSize, style, theme, textStyle } = this.props;
```
Comment (satya164) [inline src/components/Avatar/AvatarText.tsx]: labelStyle?

Comment (wojteg1337) [reply src/components/Avatar/AvatarText.tsx]: damn im drunk
