### PR TITLE
fix: fix position of menu when dimensions change

### LINKED ISSUE #3515: Menu position is wrong when changing size of window
### Current behaviour
The position of the menu does not update when changing size of the browser window.

### Expected behaviour
Menu position should render at the anchor that I have specified in the code.

### How to reproduce?
Go to the snack below. Choose web as client, make the preview show in a separate window.
Show the menu, close the menu, make the window more wider. Try to open the menu again. It should render at "show menu" but is instead rendered at the position the "show menu" button first was rendered.

https://snack.expo.dev/@fyranollfyra/faulty-menu-position-when-changing-size

(the same goes for the height also actually. Take the same separate browser window and make it the smallest height. Then reload the window, expand the height as much as you can, then open the menu again. Now the height of the menu is "cropped" and you have to scroll inside the menu to get to all options).

This also happens on iOS for example. Run the snack in Expo Go with your device in portrait mode. Turn it to landscape and the menu renders in the wrong place.

### Preview

Width:
image
image

Height: 
image
image

### What have you tried so far?
It works fine with 5.0.0-rc.8, but after that version this could be reproduced by following the above steps.

### Your Environment

| software                      | version
| --------------------- | -------
| react-native                | 0.70.5
| react-native-paper    | 5.0.1
| node                            | 16.13.1
| yarn                             | 1.22.9
| expo sdk                     | 47.0.0

### PR DESCRIPTION
**Pull request by mathias-berg**
### Summary

The dimensions was set outside the component and therefore didn't change when the screen size was adjusted.
This was introduced in in rc9 so I just moved it back to where it was before when it worked.

Fixes #3515

### CODE REVIEW

**Comment by mathias-berg** [comment]
@lukewalczak 
Is solution good for you or should I change it to an event listener and set the values in state instead?

**Comment by lukewalczak** [comment]
Hey @mathias-berg, thanks for fix! We can stick with the current approach, however I would like to confirm whether it doesnt interfere with the previously fixed issue.

**Comment by lukewalczak** [comment]
Unfortunately, the current approach with updating window dimensions breaks the `Menu` example when opening the keyboard, from the previous issue, presented on that [snack](https://snack.expo.dev/@react-native-paper/menu-with-keyboard). Looks like we need to find another solution which covers both cases.

**Comment by mathias-berg** [comment]
I will look at this tonight to see if I find a solution.

**Comment by mathias-berg** [comment]
Did a lot of investigating on this last night and found a solution that works. I will do some more testing and then update this PR.

**Comment by mathias-berg** [comment]
Changes are up now, please have a look.

**Comment by lukewalczak** [comment]
Thanks @mathias-berg! I will review & test in my spare time

File: src/components/Menu/Menu.tsx [hunk 1]
```diff
@@ -176,6 +178,7 @@ class Menu extends React.Component<Props, State> {
     anchorLayout: { width: 0, height: 0 },
     opacityAnimation: new Animated.Value(0),
     scaleAnimation: new Animated.ValueXY({ x: 0, y: 0 }),
+    windowLayout: Dimensions.get('window'),
```
Comment (lukewalczak) [inline src/components/Menu/Menu.tsx:181]: Can we narrow `windowLayout` state only to `width` and `height`?

File: src/components/Menu/Menu.tsx [hunk 2]
```diff
@@ -384,11 +392,30 @@ class Menu extends React.Component<Props, State> {
   };
 
   private keyboardDidShow = (e: RNKeyboardEvent) => {
-    this.keyboardHeight = e.endCoordinates.height;
+    const keyboardHeight = e.endCoordinates.height;
+    const windowLayout = Dimensions.get('window');
```
Comment (lukewalczak) [inline src/components/Menu/Menu.tsx:396]:
```suggestion
    const { width, height } = Dimensions.get('window');
```

File: src/components/Menu/Menu.tsx [hunk 3]
```diff
@@ -384,11 +392,30 @@ class Menu extends React.Component<Props, State> {
...
+
+    this.setState({
+      windowLayout: {
+        height: windowLayout.height - keyboardHeight,
```
Comment (lukewalczak) [inline src/components/Menu/Menu.tsx:400]:
```suggestion
        height: height - keyboardHeight,
```

File: src/components/Menu/Menu.tsx [hunk 4]
```diff
@@ -384,11 +392,30 @@ class Menu extends React.Component<Props, State> {
...
+        width: windowLayout.width,
```
Comment (lukewalczak) [inline src/components/Menu/Menu.tsx:401]:
```suggestion
        width,
```

File: src/components/Menu/Menu.tsx [hunk 5]
```diff
@@ -384,11 +392,30 @@ class Menu extends React.Component<Props, State> {
...
+      },
+    });
   };
 
   private keyboardDidHide = () => {
-    this.keyboardHeight = 0;
+    const height = Dimensions.get('window').height;
```
Comment (lukewalczak) [inline src/components/Menu/Menu.tsx:407]:
```suggestion
    const { height } = Dimensions.get('window');
```

File: src/components/Menu/Menu.tsx [hunk 6]
```diff
@@ -384,11 +392,30 @@ class Menu extends React.Component<Props, State> {
...
+    this.setState((state) => ({
+      windowLayout: {
+        width: state.windowLayout.width,
+        height,
+      },
+    }));
+  };
+
+  private onWindowChangeHandler = ({ window }: { window: WindowLayout }) => {
+    this.setState({ windowLayout: window });
```
Comment (lukewalczak) [inline src/components/Menu/Menu.tsx:418]: Accordingly to the first comment, please update there only `width` and `height`

File: src/components/Menu/Menu.tsx (hunk 1 above)
Comment (mathias-berg) [reply src/components/Menu/Menu.tsx:181]: Of course, fixing it!

File: src/components/Menu/Menu.tsx (hunk 2 above)
Comment (mathias-berg) [reply src/components/Menu/Menu.tsx:396]: Fixed!

File: src/components/Menu/Menu.tsx (hunk 3 above)
Comment (mathias-berg) [reply src/components/Menu/Menu.tsx:400]: Fixed!

File: src/components/Menu/Menu.tsx (hunk 4 above)
Comment (mathias-berg) [reply src/components/Menu/Menu.tsx:401]: Fixed!

File: src/components/Menu/Menu.tsx (hunk 5 above)
Comment (mathias-berg) [reply src/components/Menu/Menu.tsx:407]: Fixed!

File: src/components/Menu/Menu.tsx (hunk 6 above)
Comment (mathias-berg) [reply src/components/Menu/Menu.tsx:418]: Fixed!

**Review by lukewalczak — APPROVED** [review]
Hey @mathias-berg, thanks for the help with fixing the issue! 🎉
