### PR TITLE
Fix RadioButton onPress

### LINKED ISSUE #1355: OnPress event on radio button does not work
## Environment

react-native  0.60.4
react-native-paper 2.16.0

## Description

When I pass the function to the RadioButton prop OnPress, the event doesn't fire no matter how many times I press the button.

## Reproducible Demo

The example itself passed by the documentation is enough to reproduce the error.

```javascript
import * as React from 'react';
import { View } from 'react-native';
import { RadioButton } from 'react-native-paper';

export default class MyComponent extends React.Component {
  state = {
    checked: 'first',
  };

  render() {
    const { checked } = this.state;

    return (
      <View>
        <RadioButton
          value="first"
          status={checked === 'first' ? 'checked' : 'unchecked'}
          onPress={() => { this.setState({ checked: 'first' }); }}
        />
        <RadioButton
          value="second"
          status={checked === 'second' ? 'checked' : 'unchecked'}
          onPress={() => { this.setState({ checked: 'second' }); }}
        />
      </View>
    );
  }
}
```

### PR DESCRIPTION
**Pull request by Taym95**
Fix #1355

### CODE REVIEW

File: src/components/RadioButton.tsx [hunk 1]
```diff
@@ -114,7 +114,7 @@ class RadioButton extends React.Component<Props> {
     const { onPress } = this.props;
     const { onValueChange } = context;
 
-    onPress || onValueChange(this.props.value);
+    onPress ? onPress() : onValueChange(this.props.value);
```
Comment (Trancever) [inline src/components/RadioButton.tsx]: Please change line 135 to this: 
```
            onPress={
              this.props.onPress ||
              (() => {
                context && this.handlePress(context);
              })
            }
```

This change is also needed to make it fully working

Comment (Taym95) [reply src/components/RadioButton.tsx]: Yes sure I will, I have a question what if context is null this `const { onValueChange } = context || {};` will not throw an error?

Comment (Trancever) [reply src/components/RadioButton.tsx]: It will, but context will be undefined when RadioButton is not wrapped with RadioButton.Group. You can double check that but I am pretty sure that's how context should work.

Comment (Taym95) [reply src/components/RadioButton.tsx]: This one `const { onValueChange } = context || {};` will trigger this typescript error `Initializer provides no value for this binding element and the binding element has no default value.` because Typescript notices that `onValueChange ` is not present in `{}`.

Comment (Trancever) [reply src/components/RadioButton.tsx]: It's fine, let's do this
