### PR TITLE
fix: input label not visible on ios if multiline, fixes #4482

### LINKED ISSUE #4482: Label is hidden when a multiline TextInput is focused on iOS
### Current behaviour
When focusing into a TextInput (at least when mode='flat'), the label disappears. It shows up normally when multiline=false, and this is only a problem on iOS.

### Expected behaviour
For the label to be scaled down and shown as usual.

### Preview
Screenshot 2024-08-21 at 14 10 38
Screenshot 2024-08-21 at 14 10 44

### What have you tried so far?
I've traced the problem down to this code in `TextInputFlat.tsx`, commenting it out solves the problem.

```
{!isAndroid && multiline && !!label && !disabled && (
    // Workaround for: https://github.com/callstack/react-native-paper/issues/2799
    // Patch for a multiline TextInput with fixed height, which allow to avoid covering input label with its value.
    <View
      testID="patch-container"
      pointerEvents="none"
      style={[
        StyleSheet.absoluteFill,
        dense ? styles.densePatchContainer : styles.patchContainer,
        {
          backgroundColor:
            viewStyle.backgroundColor || containerStyle.backgroundColor, **// <-- commenting out this line fixes the issue.**
          left: paddingLeft,
          right: paddingRight,
        },
      ]}
    />
  )}
```

### Your Environment

| software                      | version
| --------------------- | -------
| react-native                | 0.74.1
| react-native-paper    | 5.12.5

### PR DESCRIPTION
**Pull request by damianfilipek81**
### Motivation

This PR solves this [issue](https://github.com/callstack/react-native-paper/issues/4482). "When focusing into a TextInput (when mode='flat'), the label disappears. It shows up normally when multiline=false, and this is only a problem on iOS."

### Related issue

[issue](https://github.com/callstack/react-native-paper/issues/4482)

### Test plan

I've checked it on ios simulator and android emulator, since example project is on expo 48 i cannot install it on my phone.
I've also updated `TextInput.test.tsx.snap` snapshot since tests were failing.

### CODE REVIEW

**Comment by iM-GeeKy** [comment]
@gedu Is this planned to be merged? Still an issue in `5.12.5`.

**Comment by ericpoulinnz** [comment]
@gedu @BogiKay any plans on merging this in now that new arch is supported?

File: src/components/TextInput/Label/InputLabel.tsx [hunk 1]
```diff
@@ -138,7 +138,7 @@ const InputLabel = (props: InputLabelProps) => {
     // This gives the effect of animating the color, but allows us to use native driver
     <View
       pointerEvents="none"
-      style={[StyleSheet.absoluteFill, styles.overflow]}
```
Comment (BogiKay) [inline src/components/TextInput/Label/InputLabel.tsx:141]: I don't think we need to apply `styles.labelContainer` twice. Can you get rid of it from line `147`?

**Review by BogiKay — CHANGES_REQUESTED** [review]
I tested the fix and works good, the issue is gone. I just found one little improvement that can be done. Beside that all good 👍

**Comment by ericpoulinnz** [comment]
Worth checking that this PR fixes the issue on web as well. Since I posted the issue (#4482) I found this also is a problem on web.

**Comment by BogiKay** [comment]
@ericpoulinnz I tested it and the issue is gone on web as well

**Review by BogiKay — APPROVED** [review]

**Comment by ericpoulinnz** [comment]
@BogiKay any chance a new version can be pushed out now that this fixed is merged in?
