### PR TITLE
fix: use same color and size for button text and icon

### LINKED ISSUE #1725: Set icon color on a <Button />
I'd like to be able to control the icon's color on ` Button` so that it matches the `textColor` that I am manually setting via `labelStyle`. 

I have a PR that I will submit that adds `Button.iconColor`. Another alternative is to allow specifying `Button.iconProps`.

### PR DESCRIPTION
**Pull request by Trancever**
### Motivation

Fix #1725 

### Test plan

Screenshot 2020-05-05 at 17 05 18
Screenshot 2020-05-05 at 17 05 48

### CODE REVIEW

File: src/components/Button.tsx [hunk 1]
```diff
@@ -279,13 +283,17 @@ class Button extends React.Component<Props, State> {
           <View style={[styles.content, contentStyle]}>
             {icon && loading !== true ? (
               <View style={styles.icon}>
```
Comment (satya164) [inline src/components/Button.tsx:285]: Maybe we should also add `width` here like before?

Comment (Trancever) [reply src/components/Button.tsx:285]: I was thinking about it. I decided to keep it as it is now, cause I couldn't break it :D I am gonna try it one more time to make sure it works properly.
