### PR TITLE
fix: progress bar animated value

### LINKED ISSUE #3366: Stacktrace when using animation with progressbar
Hi guys, does this seem ok to you ?
https://snack.expo.dev/@flaze9/progressbar?name=ProgressBar&description=https%3A%2F%2Fcallstack.github.io%2Freact-native-paper%2F4.0%2Fprogress-bar.html&code=import%20*%20as%20React%20from%20%27react%27%3B%0Aimport%20%7B%20ProgressBar%2C%20Colors%20%7D%20from%20%27react-native-paper%27%3B%0A%0Aconst%20MyComponent%20%3D%20()%20%3D%3E%20(%0A%20%20%3CProgressBar%20progress%3D%7B0.5%7D%20color%3D%7BColors.red800%7D%20%2F%3E%0A)%3B%0A%0Aexport%20default%20MyComponent%3B&dependencies=react-native-paper

Because i have issues making it work in my code, the above snack is a minimal example

Screenshot 2022-09-13 at 21 58 46

This is what I get in local
Would greatly appreciated some help

### PR DESCRIPTION
**Pull request by hurali97**
### Summary

Fixes #3366

Introduces the `animatedValue` prop to allow usage for controlling the progress bar using animated value created by Animated API. This prop is different when compared to `progress`, since progress isn't designed to support values that change continuously as it triggers another animation under the hood to populate progress bar. So we allowed the users to pass in their own `animatedValue` to control the progress bar.

### Test plan

<details>
<summary>android</summary>

https://user-images.githubusercontent.com/47336142/196183132-227320fd-1561-47e1-83f6-0e893aeeda41.mp4

</details>

<details>
<summary>iOS</summary>

https://user-images.githubusercontent.com/47336142/196184210-cba73bab-4dda-46ca-a72c-07bdbd00b8f5.mp4

</details>

<details>
<summary>web</summary>

https://user-images.githubusercontent.com/47336142/196185416-34854a4b-45b4-44d6-9e7d-691da65e3a04.mp4

</details>

### CODE REVIEW

File: src/components/ProgressBar.tsx [hunk 1]
```diff
@@ -16,8 +16,14 @@ import { withTheme } from '../core/theming';
...
 
 export type Props = React.ComponentPropsWithRef<typeof View> & {
+  /**
+   * Animated value (between 0 and 1). This tells the progress bar to rely on this value to animate it.
+   * Should not be used with progress prop.
+   */
+  animatedValue?: number;
   /**
    * Progress value (between 0 and 1).
+   * Should not be used with animatedValue prop.
```
Comment (lukewalczak) [inline src/components/ProgressBar.tsx:26]:
```suggestion
   * Note: It should not be used parallelly with `animatedValue` prop.
```

File: src/components/ProgressBar.tsx [hunk 2]
```diff
@@ -16,8 +16,14 @@ import { withTheme } from '../core/theming';
 import type { Theme } from '../types';
 
 export type Props = React.ComponentPropsWithRef<typeof View> & {
+  /**
+   * Animated value (between 0 and 1). This tells the progress bar to rely on this value to animate it.
+   * Should not be used with progress prop.
```
Comment (lukewalczak) [inline src/components/ProgressBar.tsx:21]:
```suggestion
   * Note: It should not be used parallelly with the `progress` prop.
```

Comment (hurali97) [reply src/components/ProgressBar.tsx:21]: Thanks 🚀
