### PR TITLE
Check if manager is not null for update and unmount and fix the doc

### LINKED ISSUE #991: Modal Snack Is Broken
## Environment

N/A as it's  an online snack

## Description

When the modal snack is run the following error is shown: 
image

## Reproducible Demo

[Demo link
](https://snack.expo.io/@alexmachin1997/bW9kYW?name=Modal&description=https%3A%2F%2Fcallstack.github.io%2Freact-native-paper%2Fmodal.html&code=import%20*%20as%20React%20from%20%27react%27%3B%0Aimport%20%7B%20Modal%2C%20Portal%2C%20Text%2C%20Button%2C%20Provider%20%7D%20from%20%27react-native-paper%27%3B%0A%0Aexport%20default%20class%20MyComponent%20extends%20React.Component%20%7B%0A%20%20state%20%3D%20%7B%0A%20%20%20%20visible%3A%20false%2C%0A%20%20%7D%3B%0A%0A%20%20_showModal%20%3D%20()%20%3D%3E%20this.setState(%7B%20visible%3A%20true%20%7D)%3B%0A%20%20_hideModal%20%3D%20()%20%3D%3E%20this.setState(%7B%20visible%3A%20false%20%7D)%3B%0A%0A%20%20render()%20%7B%0A%20%20%20%20const%20%7B%20visible%20%7D%20%3D%20this.state%3B%0A%20%20%20%20return%20(%0A%20%20%20%20%20%20%3CPortal%3E%0A%20%20%20%20%20%20%20%20%3CModal%20visible%3D%7Bvisible%7D%20onDismiss%3D%7Bthis._hideModal%7D%3E%0A%20%20%20%20%20%20%20%20%20%20%3CText%3EExample%20Modal%3C%2FText%3E%0A%20%20%20%20%20%20%20%20%3C%2FModal%3E%0A%20%20%20%20%20%20%20%20%3CButton%0A%20%20%20%20%20%20%20%20%20%20style%3D%7B%7B%20marginTop%3A%2030%20%7D%7D%0A%20%20%20%20%20%20%20%20%20%20onPress%3D%7Bthis._showModal%7D%0A%20%20%20%20%20%20%20%20%3E%0A%20%20%20%20%20%20%20%20%20%20Show%0A%20%20%20%20%20%20%20%20%3C%2FButton%3E%0A%20%20%20%20%20%20%3C%2FPortal%3E%0A%20%20%20%20)%3B%0A%20%20%7D%0A%7D&dependencies=react-native-paper)

### PR DESCRIPTION
**Pull request by Taym95**
Fix #991

### CODE REVIEW

File: src/components/Portal/PortalConsumer.js [hunk 1]
```diff
@@ -26,10 +26,26 @@ export default class PortalConsumer extends React.Component<Props> {
   }
 
   componentDidUpdate() {
+    if (!this.props.manager) {
```
Comment (jaysbytes) [inline src/components/Portal/PortalConsumer.js]: Can you please extract this condition to separate class method? Do not forget to prefix the name with `_` as it is a private method and place it before just before render function. Thank you for the PR!

Comment (jaysbytes) [reply src/components/Portal/PortalConsumer.js]: Or extract just error throwing. Decide what will be better for readability.
